spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${FLYWAY_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
secret:
  token: ${AUTH_SECRET}
  inference-url: ${INFERENCE_URL}
server:
  port: ${SERVER_PORT}
